### ISSUE TITLE
Add @keywords

### ISSUE THREAD

**Issue by dsweber2** [cmu-delphi/epidatr#154]
per suggestion by @dajmcdon:

> To view “all possible endpoints”, we could add @keyword tags to each of their documentation files. This has 2 benefits. One is that this can be easily (and quickly) searched. So we could write a small helper, say, available_endpoints(), that would just list them all. If we add more later, we just remember to add the same keyword to the epicall function. The second benefit is that the _pkgdown.yml reference index can contain has_keyword(…), so we don’t need to list all the endpoints individually. Since this (and likely lots of other parts of the documentation) are shared across all signals, we could even extract anything shared to a single doc. I can probably do this as a PR if others think it would be worth having.

**Comment by dshemetov** [comment]
closed by https://github.com/cmu-delphi/epidatr/issues/154

**Comment by dajmcdon** [comment]
Logging a pain point for posterity:

Despite adding `@keyword endpoint` in the Roxygen, these turn out not to create "keywords" in `help.search()`. The reason is that there is a list of [standardized keywords](https://roxygen2.r-lib.org/reference/tags-index-crossref.html) and "endpoint" isn't among them. I believe that, because it's non-standard, and even though it's still converted to `\keyword{endpoint}` in the `.Rd` file, it actually gets stored as a "concept". 

This was super annoying to try to figure out. You can view the standard keywords with `file.show(file.path(R.home("doc"), "KEYWORDS")) `

So, once #155 is merged, `help.search(package = "epidatr", keyword = "endpoint")` will find nothing, but `help.search("endpoint", package = "epidatr", fields = "concept")` will list all the endpoints.
