### ISSUE TITLE
Figure out better API key management

### ISSUE THREAD

**Issue by dsweber2** [cmu-delphi/epidatr#181]
See the [tooling notes for Sept 19th](https://docs.google.com/document/d/15e5Fw4z3qFTntZKg3ModLCHV-z2-bWZec1zIr8rWjZ0/edit#heading=h.xwx1v0352dpw)

**Comment by dshemetov** [comment]
So here is my thinking for what to do after this week's discussions:
1. move away from R options; switch `set_api_key()`  to use env vars now and remove the options check. R options aren't great for long-term safety (since they don't get read into by something like `.Renviron`) and they aren't very user friendly anyway.
2. make sure we point users to `usethis::edit_r_environ()` for a decent persistence solution 
3. write a vignette that goes into a bit more detail about how all this works
4. research other persistence libraries (keyrings, gitcreds, etc.) to see if there's something that can support the ideal workflow

The ideal workflow would be: `set_api_key()` prompts the user for an API key (sets the env var under the hood) and then prompts again with "do you want to store this API key for future sessions?" and then stores the key _somewhere_. All future session will need to make sure to read from _somewhere_ on startup. 

This difficulty is that this _somewhere_ is unclear:
1. should it be in .Renviron in the local project folder? 
2. should it be in .Renviron in the user's home directory? 
3. should it be in [XDG_CONFIG_HOME](https://specifications.freedesktop.org/basedir-spec/latest/index.html#introduction)? (e.g. `~/.config/` on Linux, `~/Library/Preferences` on Mac, ??? on Windows); `tools::R_user_dir()` can automatically find this, but it's only supported by R >= 4.0

The drawback with (1) is that the user will need to set their key every time they start a new project. The drawback with (2) and (3) is that we don't know how to find a user's home directory or their config directory _in a cross-platform way_. The additional drawback with (2) is that if the user has .Renviron in their local project (where they set variables for some other package), then the global one won't be read.

Alex recently pointed me to [`fs::path_expand`](https://fs.r-lib.org/reference/path_expand.html), which might make (2) or (3) viable.

**Comment by capnrefsmmat** [comment]
Question: Is there a situation, maybe in a production environment, where one user would need multiple API keys?

**Comment by dshemetov** [comment]
Oh man, I hope not. On the plus side, from seeing how AWS and Github handle their keys (i.e., also by reading from system env vars by default, `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` and `GITHUB_PAT`), doesn't seem like they're concerned about that situation?

**Comment by capnrefsmmat** [comment]
It's pretty easy to switch out environment variables; if you have some automation system that runs your data pipeline, you can easily set custom environment variables in the shell scripts or commands that it runs to do the various tasks.

I'm asking because the answer might change how we store the keys. Environment variables are a good option exactly because they're so easy to replace or override in specific circumstances, if that will be necessary in a production environment.

**Comment by dsweber2** [comment]
The only thing that might prompt different keys would be different private endpoint access, but in that case I think we'd just make a dedicated key instead.

**Comment by dshemetov** [comment]
Right, if we ever run integration tests with this client with privileged and unprivileged keys, env vars would be easy to swap out.

**Comment by dshemetov** [comment]
Alright, I went looking for other R developers with the same problem and I think I found a persistence solution. [This email from 2018 by Gabor Czardi](https://www.mail-archive.com/r-package-devel@r-project.org/msg02460.html) points to [rappdirs](https://github.com/r-lib/rappdirs) made exactly for the purpose, which requires only R (>= 3.2).

I'm thinking the workflow could now be something like: 
1. if interactive, `epidatr::set_api_key(SECRET_KEY)` will set the environment variable and then ask the user if they want to persist their key, with all the appropriate stern prodding that they probably should
2. if the user types "yes", then we write the key to `rappdirs::user_config_dir("epidatr")` and we print that location information
3. upon loading `epidatr`, we automatically read the key from `rappdirs::user_config_dir("epidatr")`, load it to the env var, and we print the path of the file we read from and the env var we read into

This covers all the desirable pieces I can think of:
- platform-independent persistence
- clarity about where the keys are persisted on the file system
- clarity about where the keys are read from in each session (the env var)
- the ability to modify the key per session
- proper instruction about 
- no file-system management for most users, but power users have the ability to modify the internals

**Comment by dshemetov** [comment]
Oh and we can also think about suggesting users use `rappdirs::user_cache_dir("epidatr")` for the cache.

**Comment by dshemetov** [comment]
@brookslogan points out that it's probably better to use `rappdirs::user_config_dir("R", version = "epidatr")` to organize R configs and consistency with R tools (>= 4.0).
```r
r$> rappdirs::user_config_dir("R", version = "epidatr")
[1] "~/.config/R/epidatr"
r$> tools::R_user_dir("epidatr", "config")
[1] "/home/forecaster/.config/R/epidatr"
```

**Comment by brookslogan** [comment]
Another note on [CRAN policies](https://cran.r-project.org/web/packages/policies.html)' requirement/suggestion:

> packages may store user-specific data, configuration and cache files in their respective user directories obtained from tools::R_user_dir()

According to this scheme, is sounds like for *cache* files they'd want us to use

```r
tools::R_user_dir("epidatr", "cache")
```
which is /home/<username>/.cache/R/epidatr on my Fedora system.

(Anyway, whatever location is chosen it sounds better if the API key is not in the cache directory, which using `config`/`"config"` above already achieves.  That's the main thing I'm checking on.  But it would be nice actually to have cache files in .cache so if I run low on space I can quickly clear out caches from multiple programs easily.)

**Comment by dshemetov** [comment]
Agreed. So to reiterate, I think we should:
- suggest `rappdirs::user_cache_dir("R", version = "epidatr")` by default for the cache folder, unless the user specifies otherwise
- use `rappdirs::user_config_dir("R", version = "epidatr")` for the API key storage (with confirmation), unless the user specifies otherwise

**Comment by capnrefsmmat** [comment]
Just peeking through CRAN to see what people do with API keys. Here are a few examples:

* [eia](https://cran.r-project.org/web/packages/eia/vignettes/api.html) uses an environment variable and assumes you can edit Renviron
* [rscopus](https://cran.r-project.org/web/packages/rscopus/vignettes/api_key.html) does the same
* [civis](https://cran.r-project.org/web/packages/civis/readme/README.html) too
* [cfbfastR](https://cran.r-project.org/web/packages/cfbfastR/readme/README.html) uses an environment variable and points at usethis to edit your Renviron easily
* [openai](https://cran.r-project.org/web/packages/openai/readme/README.html) does the same
* [twfy edits your Renviron for you](https://github.com/conjugateprior/twfy/blob/8855b20584d9b757b6822b81d7409caa7d2d579a/R/twfy.R#L5-L34)
* [so does ipums](https://github.com/ipums/ipumsr/blob/c7a7ec068cfbb369c6b0a59bff94d0f00de3ee6d/R/api_helpers.R#L76-L91), in a more careful way.

I can't find anyone who writes their own separate API key file.

I prefer the environment variable approach because it's [very easy to temporarily replace an environment variable](https://withr.r-lib.org/reference/with_envvar.html), e.g. for testing or because specific code needs access to different data.

Is the motivation for using `rappdirs::user_config_dir()` purely that we think using `usethis::edit_r_environ()` (even automatically, through some kind of function) will still be too complicated for some of our users, because they manually have to edit and save the file?

**Comment by dshemetov** [comment]
Thanks for doing that research into other packages. My main example was [AWS CLI](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html) which has an `~/.aws/credentials` file and I took that to be authoritative. I suppose it's better to compare with other R packages, but I think I'm just not a fan of `.Renviron`. 

Here is another issue with it, other than the one you mention (where we have to teach the user how to format the environ key line): if someone already has an  `.Renviron` in their project directory, _it doesn't combine with env vars from the home directory `.Renviron`_ so them using `usethis::edit_r_environ()` will confusingly be a no-op.

I want to clarify that my suggestion to use `rappdirs::user_config_dir()` is just for key persistence. When that file is read by epidatr, I agree that we should just load that value into `DELPHI_EPIDATA_API_KEY` env var or something like that.

**Comment by capnrefsmmat** [comment]
I think AWS does that because it has a complex configuration with a bunch of variables in different groups, and cramming that all into environment variables would be hard.

Could we check for the presence of a project-specific `.Renviron` before calling `usethis::edit_r_environ()`? It does take a `scope = "project"` argument, so if we know the project already has an `.Renviron`, we could open that for editing. We could look in the [project directory](https://usethis.r-lib.org/reference/proj_utils.html) to see if there's an `.Renviron`, for instance.

**Comment by dshemetov** [comment]
Makes sense about AWS.

And that's a good idea RE: dynamically adjusting Renviron scope. I just tested `file.exists(usethis::proj_path(".Renviron"))` and it seems to be a good way to check if a project-level Renviron exists. 

So I think that removes my objections to Renviron. @brookslogan was it your ESS setup that didn't play well with `usethis::edit_r_environ()` or am I misremembering? Any other objections to just using Renviron for key persistence after all?

**Comment by brookslogan** [comment]
Issue skirted now:
- `scope = "project"` will generate an error if it doesn't seem like you are in a project.  If we do this dynamic thing, then maybe that's not an issue.

Issues I thought there were but are resolved or partially resolved or never existed:
- I thought it didn't create new `.Renviron`s in the right place or maybe didn't read `.Renviron`s right if you were in a subdirectory of the project.  Doesn't seem to be an issue now.
- ESS at some point would always launch shells in the directory containing the script you were starting them from.  Now it will launch it at roots of git repos; **I'm not sure if it's aware of RStudio project metadata files though**.

Remaining issue:
- Uses some very-surprising project-location caching mechanism, maybe from `here`.  So if you are in one project directory and do something that triggers that mechanism and then `setwd` to outside of the project / to another project and do `usethis::edit_r_environ()`, it will edit the first project's `.Renviron`.

**Comment by dshemetov** [comment]
Couldn't a user that `setwd`'s to another project to set keys just... set their key in the first project and be fine?

**Comment by brookslogan** [comment]
Sure, but they might think "I already set that for this project, why are you saying I didn't?"  Doesn't sound the worst thing to have to set it twice and project switching isn't that common, but somehow I thought I remembered `here` caching frustrations being a recurring frustration in the past, so I don't know if I'm just missing whatever the workflow was that was frustrating or if it doesn't apply to API key setting.

**Comment by brookslogan** [comment]
For "set their key in the first project and be fine", that'd be true only if they launched within that project every time, or set it for the second project as well.  I guess that's sort of closer to how `.Renviron`s work anyway, which might be good.  (Closer, but not exact... `.Renviron`s are read at a different time than `here` location is cached; if there is a setwd between it could be a mismatch.)

**Comment by dshemetov** [comment]
On the general point of `setwd`-ing outside of a project and using `here` having unexpected behavior. That's an issue from a bad interaction upstream from us, so I wouldn't worry about it. 

And as to users changing their launch directory for projects... YAGNI, let's wait for an actual user to have this complaint. Worst case scenario is they set their key twice.
