### ISSUE TITLE
API key vignette

### ISSUE THREAD

**Issue by dsweber2** [cmu-delphi/epidatr#182]

**Comment by nmdefries** [comment]
Is this complicated enough that we need a whole vignette? What are you imagining for this?

**Comment by dshemetov** [comment]
This issue is probably obsolete, p sure it's just a bullet from a meeting before the discussions that led to #181. The description in `get_api_key()` seems pretty clear to me. I suppose we could write a vignette that assumes a user who is not used to environment variables at all and walks them through that, but that seems low priority to me.
