### ISSUE TITLE
Consider adding download caching to the client

### ISSUE THREAD

**Issue by dshemetov** [cmu-delphi/epidatr#29]
I would think the following are higher priority than trying to implement streaming:
- Tools to cache and perform smart updates on the cache.
- ...

_Originally posted by @brookslogan in https://github.com/cmu-delphi/delphi-epidata-r/issues/13#issuecomment-1079378956_

We have work on adding data caching to evalcast [here](https://github.com/cmu-delphi/covidcast/pull/580). There is the option of porting that logic here. It would be natural to keep data-fetching/caching logic contained in this package. Then evalcast and the packages that supersede it can simply be updated to use this client and get caching functionality for free.

**Comment by brookslogan** [comment]
A few caching approaches based on complexity, featurefulness, efficiency, package:
- evalcast caching port: simple-ish (see functional PR link above) but requires inspecting each endpoint we improve, latest and as_of queries over all geos of a geo type (will require updates for endpoints that don't use "*", maybe for those that use weeks instead of dates, that have different additional keys than covidcast (which has data_source, signal), etc.), can be inefficient in bandwidth & disk space, could belong in this package
- disk-backed, updating epi_archive: medium complexity (but only requires individual endpoint treatment if it lands in this package), roughly same features as evalcast port for delphi-epidata but might apply to non-delphi-epidata sources, more bandwidth- and disk- efficient, not sure which package
- smart cache  --- something like the updating epi_archive but not requiring the entire history downloaded nor a fixed set of geos: highest complexity and requires inspecting each endpoint to cache, most featureful, overhead on some access patterns, would belong in this package

Anything requiring interaction with individual endpoints may suffer from needing to think about details and bugs in the individual endpoints, so it probably would just be applied to a few of the endpoints.

I think the two major development approaches would be:
- first implement the evalcast port, then the updating full-history fixed-geo-set epi_archive, then the smarter-updating epi_archive and build using it into the endpoints
- jump to the updating full-history fixed-geo-set epi_archive and don't build it into the endpoints

And an orthogonal detail: we sometimes have updates to an issue within its publication window (plus replication delays), so real-time queries of that issue will not match retrospective queries of that issue.  This detail can be addressed in a few ways but might mean caching will require some careful messaging and/or be limited to advanced users.  (This is still ignoring the possibility of nonrecent history mangling in exceptional circumstances.)

**Comment by dshemetov** [comment]
_Brainstorm_: Which package should contain the caching code is a tricky design question. And it's something we want to get right ahead of time - don't want to add and then remove caching functionality later.

- it could live in this package (and/or Python)
  - con: would need to duplicate cache system in Python
- it could live in `epi_archive` (if I understand correctly that the answer to my first question above is that it's a dynamic cache store)
  - con: Python client would be left out
- it could live in its own repository, 
  - con?: is designing a common interface for R/Python feasible

_Suggestion_: I am leaning toward the latter, mostly because duplicating the caching system in two languages would take a lot of work. I also wonder if it may be a scope drift for `epi_archive`.

_Observation_: An updating caching system feels like duplicating the API server locally. Request your local store first and then request the missing / stale pieces from the remote store.

**Comment by dshemetov** [comment]
* Using the [memoize](https://github.com/r-lib/memoise) package in R, we can add disk-caching to the downloads. This is similar to what we already have in evalcast::download_signals.
        * Pro: don’t have to roll our own caching key-value system based on file identifiers, but instead have it be based on function arguments.
        * Pro: max_age will allow us to make caches that naturally expire after a day. This will allow fast iteration in one session, but not a persistent cache that stays stale.
        * Con: more code, more maintenance. Possibly something we could offer as an example in the docs instead.

**Comment by dsweber2** [comment]
So I wanted to jot down some (public) notes on comparing "out of the box" caching methods. [This post](https://blog.r-hub.io/2021/07/30/cache/) was the most extensive single discussion of options I could find (check boxes indicate ones that are superseded by others):
- [X] [storr](https://richfitz.github.io/storr/)
  last update: 2020
  plays nicely with parallelism
  same dev as thor (the next one)
- [ ] [thor](https://richfitz.github.io/thor/)
  last update: 2023
  specifically made for disk caching
  wrapper for [LMDB](http://www.lmdb.tech/doc/), a memory mapped database, written in C.
  basically an R clone of [py-lmdb](https://github.com/jnwatson/py-lmdb)
  is kind of fighting R's paradigms, and is heavily OO
  might provide cross-language cache portability
- [ ] [R.cache](https://henrikbengtsson.github.io/R.cache/)
  last (CRAN) update: 2022
  most recent issue is 2022
  doesn't seem to have a way to manage the age of the disk cache?
- [ ] [memoize](https://memoise.r-lib.org/)
  last (CRAN) update: 2021
  [R age issues](https://github.com/r-lib/memoise/issues/143)
  has an S3 caching function
  actually just a convenience wrapper for cachem
- [X] [cachem](https://cachem.r-lib.org/)
  last update: 2023
  apparently did their actual CRAN release this year
  tidyverse associated
  [pruning maybe introduces problematic delays](https://github.com/r-lib/cachem/issues/27). It's also happening every 5 seconds; for a memory object this makes sense, but a storage/disk one not so much. default amounts are definitely aimed more at memory (time in seconds, size is 200MB, etc).
- [X] handwritten
  last update: never
  I don't wanna

I'm going to experiment with thor but if folks have thoughts lmk. We thankfully have a very natural `key` as the string which was called, so we don't need the full complexity of a memorizer. This also means the cache can be shared between python and R calls (as long as the user sets the directories correctly, of course).

**Comment by dsweber2** [comment]
oh, we also need a default caching location:
- `here::here()` so that it's project specific
- tmp directory
- suggestions?

**Comment by dshemetov** [comment]
We converged on:
- default to `here::here(".epidatr_cache")`, but allow an absolute path specification
- the pro of here::here is that it's OS independent; the con of possibly leaving a trail of caches on the user's machine is preferrable to figuring out an OS independent user-config file
