### ISSUE TITLE
Add `print` S3 methods for any classes missing them (e.g., `EpiRange`)

### ISSUE THREAD

**Issue by brookslogan** [cmu-delphi/epidatr#51]
The highest-priority things to get `print` methods already have methods written, but may not be used; see #43.  However, classes like `EpiRange` may still benefit from a neater-looking `print` method.

**Comment by capnrefsmmat** [comment]
Seconding that EpiRange in particular needs a print method. For daily and weekly data, they currently print like this:

```r
epirange(as.Date("2021-01-01"), as.Date("2021-01-07"))
#> $from
#> [1] 20210101
#> 
#> $to
#> [1] 20210107
#> 
#> attr(,"class")
#> [1] "EpiRange"

epirange(202202, 202204)
#> $from
#> [1] 202202
#> 
#> $to
#> [1] 202204
#> 
#> attr(,"class")
#> [1] "EpiRange"
```

I think there should be a simple human-readable format, that (a) clearly states if it's daily or weekly, (b) puts the dates in a standard format like ISO 8601 instead of mashing components together with no spacing, and (c) is nice and compact on one line.
