### ISSUE TITLE
Use consistent naming for `covidcast` `data_source`s/`source`s 

### ISSUE THREAD

**Issue by brookslogan** [cmu-delphi/epidatr#53]
Use the same base name for data-source-associated:
- parameters to `covidcast` and related functions
- elements of `covidcast_epidata()`
- columns of `covidcast` results
- etc.

Either `source` and `sources` or `data_source` and `data_sources`.

**Comment by dshemetov** [comment]
So this is tricky because:
- source overwrites a keyword in R
- sources is misleading in `covidcast`, because it only accepts one source
- data_source(s) are both long for covidcast_epidata (which aims to be a handy autocomplete thing)

I'm going with (1), even though it feels slightly wrong: I really don't expect anyone to need the source keyword inside the `covidcast` function.
