### ISSUE TITLE
`covid_hosp_facility` does not actually support a list of hospital pks

### ISSUE THREAD

**Issue by brookslogan** [cmu-delphi/epidatr#67]
We should properly validate and document this, rather than returning data for only a single pk.

**Comment by dshemetov** [comment]
This seems like a bug with the API:
- https://delphi.cmu.edu/epidata/covid_hosp_facility/?hospital_pks=390119,100075&collection_weeks=20210101%2C%2020210108
  - returns data for both pks and for both dates
- https://delphi.cmu.edu/epidata/covid_hosp_facility/?hospital_pks=390119%2C%20100075&collection_weeks=20210101%2C%2020210108
  - returns data just for one pk and for both dates

So I think it has something to do with `covid_hosp_facility` not parsing the `%2C%20` character, but _specifically_ in the hospital_pks argument, because it clearly works in the collection_weeks argument (?!).

**Comment by melange396** [comment]
`%2C%20` is two characters; `%2C` is a comma (the delimter), but `%20` is a space (which i would argue doesnt belong in either of those variables/arguments)...  the difference is that `collection_weeks` is parsed as a integer (which apparently silently ignores the space) and `hospital_pks` is parsed as a string (so its presumably looking for two hospital ids, one of which is "`390119`" but the other is "` 100075`" and that id with the leading space does not exist in the database).

**Comment by dshemetov** [comment]
Thanks for the context @melange396. Didn't realize a space was getting in there. So the error is not in the API, but in the request param formatting in this repo. Partial bug fix in #74, need some help though.
