### ISSUE TITLE
`request_url` handling of default args and other args

### ISSUE THREAD

**Issue by dshemetov** [cmu-delphi/epidatr#84]
`print(call)` did provide "the" `request_url` by default before, but the problem is that the request URL changes based on what further options we provide; see the args to `request_url`.  If you think if a better name for request-URL-with-default-args-for-`request_url`-but-other-arguments-baked-in, please add it!

_Originally posted by @brookslogan in https://github.com/cmu-delphi/epidatr/issues/81#issuecomment-1503716037_

Ideal workflow is something like: `print(call)` by default pretty prints the args and the request url with all the correct arguments set. Implementation details unclear though.

**Comment by brookslogan** [comment]
More context:

> Question: what do you think of having print(call) provide the request_url by default (along with a pretty print of its params)? Or did you try this and run into a bug? It would be nice if the call pretty print was small enough to be viewable without scrolling (like a tibble preview). Maybe there's a pretty print package for lists that accomplishes that?

_Originally posted by @dshemetov in https://github.com/cmu-delphi/epidatr/issues/81#issuecomment-1502839924_

`cli` is supposed to take care of line wrapping, which is mostly why I used it there.  (R has some built-in utilities that help for line wrapping but to still get things exactly how you want them it requires some work; we have helpers for it in `epiprocess` but probably want to move to using `cli` since it's probably now a transitive `Imports:` rather than `Suggests:`.)  Is there an issue with how it's formatting things for you?  What list are you thinking of pretty-printing?

**Comment by dshemetov** [comment]
Oh, so the list I was thinking about was the list of all the params that `epidata_call` object used to spit out, before your changes that cleaned that all up. I don't think it's needed anymore: in #81, I modified `print.epidata_call` to automatically print the request_url using the `classic` format. So this issue will probably be closed by #81.
