### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by dshemetov** [cmu-delphi/epidatr#93]
Current coverage looks like:
```
File	       Lines	Relevant Covered Missed	Hits / Line	Coverage
R/covidcast.R	178	94	72	22	275	76.60%
R/epidatacall.R	270	89	74	15	21	83.15%
R/endpoints.R	1679	810	796	14	2	98.27%
R/model.R	181	95	94	1	186	98.95%
R/check.R	51	28	28	0	67	100.00%
R/request.R	44	18	18	0	10	100.00%
R/auth.R	35	18	18	0	8	100.00%
R/utils.R	19	6	6	0	47	100.00%
```

Generated with
```r
library(covr)
report(file="test-report.html")
```

**Comment by dsweber2** [comment]
Notes on what's not covered yet:
covidcast.R:
 - [ ] https://github.com/cmu-delphi/epidatr/blob/dev/R/covidcast.R#L34 printing `print.covidcast_data_signal`
- [ ] https://github.com/cmu-delphi/epidatr/blob/dev/R/covidcast.R#L53 `as.data.frame.covidcast_data_signal_list <- function(signals, ...)` not sure this is actually called at all (maybe implicitly?), but flips from a list with sub-components to a table.
- [ ] https://github.com/cmu-delphi/epidatr/blob/dev/R/covidcast.R#L82 `print.covidcast_data_source <- function(source, ...)` printing again
- [ ] https://github.com/cmu-delphi/epidatr/blob/dev/R/covidcast.R#L115 dealing with http error codes
- [ ] https://github.com/cmu-delphi/epidatr/blob/dev/R/covidcast.R#L150 `as.data.frame.covidcast_data_source_list <- function(sources, ...)` the source version of 53
- [ ] https://github.com/cmu-delphi/epidatr/blob/dev/R/covidcast.R#L165 `print.covidcast_epidata <- function(epidata, ...)` printing again

request.R:
- [ ] https://github.com/cmu-delphi/epidatr/blob/dev/R/covidcast.R#L34 http error code, specifically [414 request too long](https://http.cat/414).

epidatacall.R:
- [ ] https://github.com/cmu-delphi/epidatr/blob/dev/R/epidatacall.R#L71 `request_arguments <- function(epidata_call, format_type, fields = NULL)` setting `fields` in the case that its null
- [ ] https://github.com/cmu-delphi/epidatr/blob/dev/R/epidatacall.R#L82 `request_arguments <- function(epidata_call, format_type, fields = NULL)` format list argument; the only function called here `format_list` has tests though.
- [ ] https://github.com/cmu-delphi/epidatr/blob/dev/R/epidatacall.R#L93 `print.epidata_call <- function(epidata_call)` notify the user in the cli
- [ ] https://github.com/cmu-delphi/epidatr/blob/dev/R/epidatacall.R#L124 `fetch <- function(epidata_call, fields = NULL, disable_date_parsing = FALSE)` **classic call isn't tested in fetch**
- [ ] https://github.com/cmu-delphi/epidatr/blob/dev/R/epidatacall.R#L152 `fetch_tbl <- function(epidata_call, fields = NULL, disable_date_parsing = FALSE)` `fetch_tbl` called on an endpoint that only supports classic.
- [ ] https://github.com/cmu-delphi/epidatr/blob/dev/R/epidatacall.R#L190 `fetch_classic <- function(epidata_call, fields = NULL, disable_data_frame_parsing = TRUE)` classic errors untested
- [ ] https://github.com/cmu-delphi/epidatr/blob/dev/R/epidatacall.R#L219 `fetch_csv <- function(epidata_call, fields = NULL, disable_date_parsing = FALSE, disable_tibble_output = FALSE)` `fetch_csv` called on an endpoint that only supports classic.
- [ ] https://github.com/cmu-delphi/epidatr/blob/dev/R/epidatacall.R#L230 `fetch_csv <- function(epidata_call, fields = NULL, disable_date_parsing = FALSE, disable_tibble_output = FALSE)` tibble output never disabled
- [ ] https://github.com/cmu-delphi/epidatr/blob/dev/R/epidatacall.R#L248 `fetch_csv <- function(epidata_call, fields = NULL, disable_date_parsing = FALSE, disable_tibble_output = FALSE)` `col_names` never of length 0
- [ ] https://github.com/cmu-delphi/epidatr/blob/dev/R/epidatacall.R#L257 `fetch_csv <- function(epidata_call, fields = NULL, disable_date_parsing = FALSE, disable_tibble_output = FALSE)` info's type is never epiweek?
- [ ] https://github.com/cmu-delphi/epidatr/blob/dev/R/epidatacall.R#L265 `fetch_debug <- function(epidata_call, format_type = "classic", fields = NULL)` apparently never tested, though I think this is a helper tool for mocking.
- [ ] https://github.com/cmu-delphi/epidatr/blob/dev/R/epidatacall.R#L304 `with_base_url <- function(epidata_call, base_url)` also never tested. Are there even other base_url's to test this on? (besides mocking)
- [ ] https://github.com/cmu-delphi/epidatr/blob/dev/R/epidatacall.R#L324 `request_impl <- function(epidata_call, format_type, fields = NULL)` another http error not tested
- [ ] https://github.com/cmu-delphi/epidatr/blob/dev/R/epidatacall.R#L340 `print.epidata_csv <- function(x, ...)` another print
- [ ] https://github.com/cmu-delphi/epidatr/blob/dev/R/epidatacall.R#L356 `info_to_type <- function(info, disable_date_parsing = FALSE)` date parsing never disabled.
model.R:
- [ ] https://github.com/cmu-delphi/epidatr/blob/dev/R/models.R#L104-110 `parse_value <- function(info, value, disable_date_parsing = FALSE)` a couple of cases which aren't hit, like returning `null` if parsing a `null`, `info$type` is an `epiweek`, or a `bool`.
- [ ] https://github.com/cmu-delphi/epidatr/blob/dev/R/models.R#L126 `parse_data_frame <- function(epidata_call, df, disable_date_parsing = FALSE)` `meta` of length 0 never happens
- [ ] https://github.com/cmu-delphi/epidatr/blob/dev/R/models.R#L147 `parse_api_week <- function(value)` not tested at all, strangely, even though it comes up in other tests
- [ ] https://github.com/cmu-delphi/epidatr/blob/dev/R/models.R#L159 `fields_to_predicate <- function(fields = NULL)` always `NULL` in tests so mostly untested
- [ ] https://github.com/cmu-delphi/epidatr/blob/dev/R/models.R#L199 `parse_timeset_input <- function(value)` error case goes untested

endpoints.R:
- [ ] https://github.com/cmu-delphi/epidatr/blob/dev/R/endpoints.R#L91 `covid_hosp_facility_lookup <- function(state = NULL, ccn = NULL, city = NULL, zip = NULL, fips_code = NULL)` input test for missing never fails
- [ ] https://github.com/cmu-delphi/epidatr/blob/dev/R/endpoints.R#L684-690 `covidcast` same thing, parameter check never fails
- [ ] https://github.com/cmu-delphi/epidatr/blob/dev/R/endpoints.R#L887 `ecdc_ili` issues and lag
- [ ] https://github.com/cmu-delphi/epidatr/blob/dev/R/endpoints.R#L941 `flusurv` issues and lag
- [ ] https://github.com/cmu-delphi/epidatr/blob/dev/R/endpoints.R#L995 `fluview_clinical` issues and lag
- [ ] https://github.com/cmu-delphi/epidatr/blob/dev/R/endpoints.R#L1084 `fluview` issues and lag
- [ ] https://github.com/cmu-delphi/epidatr/blob/dev/R/endpoints.R#L1227 `kcdc_ili` issues and lag
- [ ]  https://github.com/cmu-delphi/epidatr/blob/dev/R/endpoints.R#L1344 `nidss_flu` issues and lag
- [ ]  https://github.com/cmu-delphi/epidatr/blob/dev/R/endpoints.R#L1601-1604 `pvt_twitter` issues and lag
- [ ]  https://github.com/cmu-delphi/epidatr/blob/dev/R/endpoints.R#L1654 `wiki` either epiweeks or dates
- [ ]  https://github.com/cmu-delphi/epidatr/blob/dev/R/endpoints.R#L1657 `wiki` creating a date for the date field rather than an epiweek

So there are a couple of broad categories untested:
- printing utilities
- some `fetch` errors
- some http error codes
- endpoint errors (mostly issues/lag being mutually exclusive
- `if` statements which had a case missing

**Comment by dsweber2** [comment]
In epidatacall.R `fetch_classic`, I don't think the check for `response_content$result != 1` is the right way to go about this.
I think `result` is never going to be `-1` or `-2`, as http errors 400, 401, 403, 405, 414, and 500 are all thrown as `R` errors earlier in request.R, while other errors make no guarantees of returning something parseable by `httr::content` and/or `jsonlite::fromJSON`. An example:
```
test_that("non-enumerated errors are passed up the chain", {
  response <- httr::RETRY("GET",
    url = "https://httpbin.org/status/418",
    query = list(),
    terminate_on = c(400, 401, 403, 405, 414, 500),
    http_headers,
    httr::authenticate("epidata", get_auth_key())
  ) %>% readr::write_rds(testthat::test_path("data/test-do_request-httpbin418.rds"))
  local_mocked_bindings(request_impl = function(...) readRDS(testthat::test_path("data/test-do_request-httpbin418.rds")))
  epidata_call <- delphi(system = "ec", epiweek = 201501)
  expect_error(epidata_call %>% fetch_classic(), class = "epidata_error")
})
```

So I'm leaving that one unchecked and untested for now

**Comment by dshemetov** [comment]
So there are 4 epidata status codes I know:
- 1 success
- 2 truncated 
- -2 no results
- -1 generic error 

All of these come out of a response with HTTP status code 200.

But yes, any of the other HTTP error codes come prior to epidata status codes.
